// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4WAqqqLea65zZIs-HqTT8ydX813w1ZC4',
    appId: '1:326279363201:web:dd823afc8165d72894eb80',
    messagingSenderId: '326279363201',
    projectId: 'flutter-test-b2e03',
    authDomain: 'flutter-test-b2e03.firebaseapp.com',
    storageBucket: 'flutter-test-b2e03.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaCBm6K8h8lZ2g1gLOMe-hVtHXQNXadas',
    appId: '1:326279363201:android:f9ccc76de9853c6094eb80',
    messagingSenderId: '326279363201',
    projectId: 'flutter-test-b2e03',
    storageBucket: 'flutter-test-b2e03.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUaj5M5_gakCj54GfDK0pG9Fpj6eZkAJI',
    appId: '1:326279363201:ios:e377eef4db6de1a594eb80',
    messagingSenderId: '326279363201',
    projectId: 'flutter-test-b2e03',
    storageBucket: 'flutter-test-b2e03.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUaj5M5_gakCj54GfDK0pG9Fpj6eZkAJI',
    appId: '1:326279363201:ios:e377eef4db6de1a594eb80',
    messagingSenderId: '326279363201',
    projectId: 'flutter-test-b2e03',
    storageBucket: 'flutter-test-b2e03.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );
}
